import { Job } from './jobs';

export const jobsData: Job[] = [
  {
    id: 'senior-financial-advisor-mumbai',
    title: 'Senior Financial Advisor',
    department: 'Finance & Advisory',
    location: 'Mumbai',
    state: 'Maharashtra',
    isRemote: false,
    isHybrid: true,
    type: 'Full-Time',
    experienceLevel: 'Mid-Level (3–5 yrs)',
    experienceMin: 3,
    experienceMax: 5,
    salaryMin: 800000,
    salaryMax: 1200000,
    description:
      'Join our advisory team to help clients across India achieve financial independence. You will design personalised financial plans, recommend suitable mutual fund portfolios, and guide families through insurance and investment decisions.',
    responsibilities: [
      'Conduct comprehensive financial health assessments for clients',
      'Design goal-based investment strategies using mutual funds, FDs, and insurance products',
      'Build and maintain long-term client relationships with regular portfolio reviews',
      'Educate clients on market trends, compounding, and disciplined investing',
      'Collaborate with the marketing team to create financial literacy content',
      'Ensure regulatory compliance with SEBI and AMFI guidelines',
    ],
    requirements: [
      'NISM-Series V-A: Mutual Fund Distributors Certification (mandatory)',
      '3-5 years of experience in financial advisory or wealth management',
      'Strong understanding of Indian mutual fund, insurance, and fixed deposit products',
      'Excellent communication skills in English and Hindi',
      'Client-first mindset with proven track record of portfolio growth',
    ],
    skills: ['Financial Planning', 'Mutual Funds', 'Client Management', 'AMFI Certified', 'Portfolio Analysis'],
    postedDate: '2026-04-05',
    isFeatured: true,
  },
  {
    id: 'digital-marketing-manager-delhi',
    title: 'Digital Marketing Manager',
    department: 'Marketing',
    location: 'Delhi NCR',
    state: 'Delhi',
    isRemote: true,
    isHybrid: false,
    type: 'Full-Time',
    experienceLevel: 'Junior (1–3 yrs)',
    experienceMin: 2,
    experienceMax: 4,
    salaryMin: 600000,
    salaryMax: 900000,
    description:
      'Drive AssetArc\'s digital presence and brand awareness. You will own our social media strategy, content calendar, SEO performance, and paid campaigns to attract new clients and establish thought leadership in financial education.',
    responsibilities: [
      'Plan and execute social media campaigns across Instagram, LinkedIn, Facebook, and Telegram',
      'Manage SEO strategy and organic search performance for assetarc.in',
      'Create and curate financial education content (blogs, reels, infographics)',
      'Run targeted Google Ads and Meta Ads campaigns with budget optimisation',
      'Track and report on campaign performance using analytics tools',
      'Collaborate with the founder to produce video content on financial literacy',
    ],
    requirements: [
      '2-4 years of digital marketing experience, preferably in fintech or financial services',
      'Proven track record of growing social media audiences and engagement',
      'Proficiency in Google Analytics, Search Console, and Meta Business Suite',
      'Strong content writing skills with ability to simplify financial concepts',
      'Experience with video editing tools is a plus',
    ],
    skills: ['Social Media', 'SEO', 'Content Marketing', 'Google Ads', 'Analytics', 'Canva'],
    postedDate: '2026-04-03',
    isFeatured: true,
  },
  {
    id: 'full-stack-developer-bangalore',
    title: 'Full Stack Developer',
    department: 'Technology',
    location: 'Bangalore',
    state: 'Karnataka',
    isRemote: false,
    isHybrid: true,
    type: 'Full-Time',
    experienceLevel: 'Mid-Level (3–5 yrs)',
    experienceMin: 2,
    experienceMax: 5,
    salaryMin: 1000000,
    salaryMax: 1800000,
    description:
      'Build and enhance the AssetArc web platform using Next.js, React, and Supabase. You will work on client-facing features like financial calculators, portfolio dashboards, and the blog CMS while maintaining performance and accessibility standards.',
    responsibilities: [
      'Develop and maintain features on the AssetArc Next.js web application',
      'Build responsive UI components using React, Tailwind CSS, and Radix UI',
      'Design and implement Supabase database schemas and API integrations',
      'Optimise web performance (Core Web Vitals, Lighthouse scores)',
      'Collaborate with the design team to implement pixel-perfect interfaces',
      'Write clean, maintainable code with proper documentation',
    ],
    requirements: [
      '2-5 years of experience with React/Next.js and TypeScript',
      'Strong proficiency in Tailwind CSS and modern CSS techniques',
      'Experience with Supabase, PostgreSQL, or similar backend services',
      'Understanding of SEO best practices and server-side rendering',
      'Familiarity with Git, CI/CD pipelines, and deployment workflows',
    ],
    skills: ['Next.js', 'React', 'TypeScript', 'Tailwind CSS', 'Supabase', 'PostgreSQL'],
    postedDate: '2026-04-01',
    isFeatured: true,
  },
  {
    id: 'client-relations-intern-pune',
    title: 'Client Relations Intern',
    department: 'Customer Success',
    location: 'Pune',
    state: 'Maharashtra',
    isRemote: false,
    isHybrid: false,
    type: 'Internship',
    experienceLevel: 'Fresher (0–1 yrs)',
    experienceMin: 0,
    experienceMax: 1,
    salaryMin: 180000,
    salaryMax: 300000,
    description:
      'Kickstart your career in financial services by supporting our client success operations. This 6-month internship offers hands-on experience in client onboarding, relationship management, and financial product understanding.',
    responsibilities: [
      'Assist in client onboarding and KYC documentation processes',
      'Support the advisory team with research and data entry',
      'Help manage client communication via email and phone',
      'Prepare client portfolio review reports and summaries',
      'Participate in team meetings and contribute to process improvements',
      'Learn fundamentals of mutual funds, insurance, and financial planning',
    ],
    requirements: [
      'Currently pursuing or recently completed a degree in Commerce, Finance, or Business Administration',
      'Strong communication skills in English and Hindi',
      'Proficiency in Microsoft Excel and Google Workspace',
      'Eagerness to learn about financial products and client management',
      'Ability to work in a fast-paced, collaborative environment',
    ],
    skills: ['Client Support', 'Excel', 'Communication', 'Financial Basics', 'Documentation'],
    postedDate: '2026-04-06',
    isFeatured: true,
  },
];
